[package]
name = "rust_lang_cn"
version = "0.1.0"
authors = ["liyuan <liyuan462@gmail.com>"]

[dependencies]
hyper = "*"
iron = "*"
router = "*"
handlebars-iron = "*"
rustc-serialize = "*"
toml = "*"
persistent = "*"