app_path = "http://localhost"
static_path = "http://localhost/static"
cookie_sign_key = "test"

[database]
host = "localhost"
port = 3306
user = "user"
password = "password"
name = "db_name"

[github]
client_id = "github_client_id"
client_secret = "github_client_secret"